bump_version: null
lint: {}
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Alaina Hardie
  description: PCA population structure analysis and plots using 1000genomes dataset
  force: true
  is_nfcore: true
  name: popinsights
  org: nf-core
  outdir: .
  skip_features: []
  version: 1.0.0dev
update: null
